### ISSUE TITLE
create command crashes

### ISSUE THREAD

**Issue by bug-brain** [solidjs-community/solid-cli#37]
I have tried multiple package managers and configurations but the commands listed under https://www.npmjs.com/package/create-solid failed everytime.
```ts
┌  
 Create-Solid v0.5.2
│
◇  Project Name
│  test
│
◇  Is this a Solid-Start project?
│  Yes
│
◇  Which template would you like to use?
│  basic
│
◇  Use Typescript?
│  Yes
│
▲  Something went wrong
```

**Comment by bug-brain** [comment]
Hey, I don't use this machine ofter for development and it turned out the version was 16.17.0. I updated and now it works so thanks for the hint!

**Comment by Tommypop2** [comment]
Awesome, no problem! Glad it's all working properly now lol
