### ISSUE TITLE
`bun create solid` or `bunx create-solid` runs forever if node is not installed

### ISSUE THREAD

**Issue by TanishqSingla** [solidjs-community/solid-cli#50]
## Description
When creating boilerplate using `bun create solid` or `bunx create-solid`, the command runs forever if node is not installed. However everything runs file if the node is already installed.

Since bun is a competing javascript runtime I assumed the bun create command must not depend on node.

**Comment by huseeiin** [comment]
this is a bun issue, not a solid issue
